/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1abb2a5d-9b86-4210-ab73-bb25603beaa3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_F1JCFKIaC",
    "aws_user_pools_web_client_id": "41538v61buc56pv68uc16b9qfi",
    "oauth": {}
};


export default awsmobile;
